### ISSUE TITLE
Creat, Update and Delete (CUD) functions missing in CQLSharp LINQ provider

### ISSUE THREAD

**Issue by fdsmax** [reuzel/CqlSharp.Linq#1]
@reuzel as mentioned in your TODO's list, seems the Create, Update and Delete functionality are missing in the current CQLSharp LINQ provider. 'SubmitChanges()' or 'SaveChanges()' support as in the standard LINQ framework would be much helpful. Any plans of this being available in the near future? 

Also, I am discussing with my team if any one of us can take up the task to add basic CUD support ('R' is already supported in CRUD) by forking your code. If it is in your tasks pipeline then we will leave it with you and would wait for you.

Currently, we are using your CQLSharp client for our new generation social network http://thulya.com . Though the 'select' with 'where' queries are working amazingly fast with the binary protocol support you had implemented, we are now stuck with missing CUD support.

Thanks for your time.

Regards,
Thulya Team

**Comment by fdsmax** [comment]
@reuzel Just an update from my end, I have been looking at DBLinq (https://code.google.com/p/dblinq2007/) code to add support for CQLSharp. Adding CUD support using DBLinq library could be easier and we could facilitate generating dbml (or edmx) classes.

**Comment by reuzel** [comment]
Hi, thanks for using CqlSharp. These kinds of comments give a boost to morale. 

That said, time is a thing that is rather scarce. I'm developing CqlSharp, and its Linq driver outside working hours. I try to find as much time as I can to work on CqlSharp and CqlSharp.Linq, and any support is very welcome. Therefore, please do not hesitate to fork CqlSharp, add and correct and issue a pull request. I'm more than happy to incorporate your improvements!

dblinq is new to me. I'll have a look on that one...

**Comment by reuzel** [comment]
As a side note, I'm also quite interested in what it would take to use CqlSharp as an underlying driver to Microsoft's EntityFramework... Any thoughts?

**Comment by fdsmax** [comment]
@reuzel thank you :-) Your efforts and time is much appreciated. Just couple of points.. 

(1) I have forked your CqlSharp.Linq. As my team too is running with tight timelines for the imminent beta release of http://thulya.com, for the time being we would implement an extension (CqlDmlExtension) on top of your CqlSharp.Linq library to handle InsertOnSubmit, UpdateOnSubmit, DeleteOnSubmit and SubmitChanges functionality with naive approach to handle the TrackedItems. Upon completion, will send you a note in case if you would like to consider pull it to your master branch. Infact, at later stage, we may appreciate if this could be implemented properly to track the modified objects using OnPropertyChanging event etc.

(2) When time permits, pl have a look at http://effiproz.codeplex.com/SourceControl/latest#EffiProz/  This project has the full implementation of the Entity Framework .Net Provider with driver setup code. You could ignore the underlying HSQL (Hyper SQL) db but refer the Entity Framework provider/driver code. Such implementation would provide entity framework support. Users would be able to use Visual Studio Server Explorer to produce cqlsharp edmx classes using CQLSharp driver, as they do with standard MSSQL ADO.Net driver. Pl note that the EffiProz derives the functions of DbProviderManifest etc and is bit different than http://www.codeplex.com/IQToolkit , cited in your notes.

(3) One good news from my team is that we have used your CQLSharp .net provider and implemented a Cassandra Management Studio and MSSQL to CQL (Cassandra) migration tool. We are yet to decide whether to release it as part of Thulya Developer tools in the forthcoming release of http://thulya.com or to release it through github.

(4) Last but not the least, once we start making revenue from our website, we will be happy to donate a bit to appreciate your efforts or we could work together remotely on interesting tasks. Pl let us know your contact email. Our contact details are at http://thulya.com/contactus.aspx

**Comment by fdsmax** [comment]
We have committed the first version of the CqlSharp.Linq.CudExtension project. 

Pl find it at:
https://github.com/thulya/CqlSharp.Linq/tree/master/CqlSharp.Linq.CudExtension

This implementation uses a very basic(or naive?) approach but a fully functional workaround to support basic insert, update and delete functions until a professional implementation of LINQ or Entity Provider is implemented with objects property changes tracking.

Simply, reference CqlSharp.Linq.CudExtension (along with CqlSharp and CqlSharp.Linq) in your project and it starts supporting the basic functions listed below:

(1) InsertOnSubmit (Similar to Add or Attach in EF)

(2) UpdateOnSubmit (This is a non-standard temporary function. LINQ and Entity Providers do not have any equivalent functions as they do track the object properties automatically using OnPropertyChanging)

(3) DeleteOnSubmit (Similar to "Remove" in EF)

(4) SubmitChanges (Similar to "SaveChanges" in EF)

A fully functional example is at:
https://github.com/thulya/CqlSharp.Linq/tree/master/LinqCudTestsConsole

Change set: https://github.com/thulya/CqlSharp.Linq/commit/03c1efd7a79fedad59cfd4953f029c214f5ea8e2  (Some of the changes in this set are customised for http://thulya.com requirement and hence pl be cautious while merging, especially with the dll reference paths).

Note: We will soon publish the CqlContext supported property classes generator (somewhat similar to dbml or edmx classes generator but with minial features compatible for CqlSharp.Linq property classes that can be straight away used as in the example above.

Thulya Team,
http://thulya.com

PS If your CqlContext.cs class does not have TrackedTables property then you may need to add the following to it :
https://github.com/thulya/CqlSharp.Linq/blob/master/CqlSharp.Linq/CqlContext.cs

```
    /// <summary>
    /// Maintains upsert and delete objects queue in dictionary until saved or till the CqlContext object disposes
    /// </summary>
    /// <remarks>This property can be eliminated upon implementing LINQ or Entity provider to support CUD</remarks>
    public HybridDictionary TrackedTables {get; set;}
```

**Comment by reuzel** [comment]
Thanks for all the effort! I will see that this will get integrated in the Linq library in some way. 

Joost

**Comment by reuzel** [comment]
Hi, I've checked in a series of changes that add ChangeTracking to the mix. The API is Entity Framework style. Please have a look and tell me what you think!

**Comment by fdsmax** [comment]
Thanks for the latest check ins @reuzel . Its much appreciated. This sounds great as we would be able to use the latest version with our site's alpha release ahead. Perhaps there seems two minor overlooked aspects: 1. ChangeTracker.cs seems missed in the check ins under Mutations folder. 2. If you would like to use the Class name (or any reserved keyword) itself as a variable or property then MS recommends to use @ symbol as a prefix to the variable. 
e.g: 
internal CqlQueryProvider @CqlQueryProvider { get; private set; } 
public ChangeTracker @ChangeTracker { get; private set; }

**Comment by reuzel** [comment]
argh, sloppy. This is fixed (with a few other things) in the latest commit. 

Note that I'm still working on this. It requires more testing, interfaces are not that stable at this moment, and performance can be improved enormously.

**Comment by fdsmax** [comment]
ok, thank you very much for the latest checkin, @reuzel . No worries.. we would ensure to test and integrate the stable versions :-)

**Comment by fdsmax** [comment]
We are testing your latest Cql linq library with our site and its working excellently, @reuzel. It was a timely release that helped us a lot. As the command timeout has been reduced from default 30 to 10, in some cases the thread has closed bit earlier so we had to increase it to 20 and it worked in our environment excellently. We would launch our beta site soon and would share the good news with you.

Regards,
Thulya Team
http://www.thulya.com
