### ISSUE TITLE
Error in invoking ProjectionReader constructor

### ISSUE THREAD

**Issue by fdsmax** [reuzel/CqlSharp.Linq#2]
The constructor in ProjectionReader is currently 'public' and hence the Activator.CreateInstance in Execute method of CqlContext class is failing with error: "Constructor on type 'CqlSharp.Linq.ProjectionReader '...' not found."

To fix this, need to add "BindingFlags.Public" to the Activator.CreateInstance. This has been fixed in the forked code at:
https://github.com/thulya/CqlSharp.Linq/commit/ae7b7263466710b005486d7cce16a933970c40b6

Thulya Team
http://thulya.com

**Comment by reuzel** [comment]
Thanks for the heads-up. Will fix this. Please do not hesitate to create an actual pull-request for these kind of changes. Allows me to merge them with a single click of the button...

**Comment by fdsmax** [comment]
Thanks for fixing this @reuzel . I was bit hesitant to send pull request as we have changed other bits too in our code branch to fit our requirements for the imminent deployment.
