### ISSUE TITLE
Quotes for identifiers and table name in query cause 'no viable alternative at input' error

### ISSUE THREAD

**Issue by fdsmax** [reuzel/CqlSharp.Linq#3]
The extra single quotes for the identifiers and the table name in the generated cql query cause 'no viable alternative at input' error.

I have applied the fix in CqlTextBuilder.cs in the forked branch at:
https://github.com/thulya/CqlSharp.Linq/commit/e3e380834fa394854323f1c69340fd4a385673f7

@reuzel , I am not sure if these single quotes for the identifiers and the table name in the generated query were meant for any other specific cases other than the 'select' query. If so then we may need to modify this a bit to handle those functions.

Thulya Team,
http://thulya.com

**Comment by reuzel** [comment]
hi

This was done on purpose. How else to deal with column or table names that have capitals? However,  I do see now that these quotes should have been double quotes ([Quoted Identifiers](http://cassandra.apache.org/doc/cql3/CQL.html#identifiers))...

**Comment by fdsmax** [comment]
Thanks for the pointer and fix, @reuzel. Sorry I overlooked it a bit. According to the Cassandra docs, could the following be a better fix?

Table names:
            builder.Append(" FROM \"");
            builder.Append(selectStatement.TableName.Replace("\"", "\"\""));
            builder.Append("\"");

Identifiers:
    value = "\"" + selector.Identifier.Replace("\"", "\"\"") + "\"";

I changed this in my branch and tested. Looks like working alright for the test cases.

**Comment by reuzel** [comment]
think you are right. I didn't do the escaping inside the identifier. Will have a look at it.

**Comment by srimay** [comment]
Hi 

I am importing an sql file to cassendra by running this below command i got an error.

$ cqlsh -f emptest.sql -k employee

emptest.sql:8:Bad Request: line 1:0 no viable alternative at input ';'
emptest.sql:9:Bad Request: line 1:0 no viable alternative at input ';'
emptest.sql:10:Bad Request: line 1:0 no viable alternative at input ';'
emptest.sql:11:Bad Request: line 1:0 no viable alternative at input ';'
emptest.sql:12:Bad Request: line 1:0 no viable alternative at input ';'
emptest.sql:13:Bad Request: line 1:0 no viable alternative at input ';'
emptest.sql:14:Bad Request: line 1:0 no viable alternative at input ';'
emptest.sql:15:Bad Request: line 1:0 no viable alternative at input ';'
emptest.sql:16:Bad Request: line 1:0 no viable alternative at input ';'
emptest.sql:17:Bad Request: line 1:0 no viable alternative at input ';'
emptest.sql:23:Invalid syntax at char 22
emptest.sql:23:  DROP TABLE IF EXISTS `emptest`;
emptest.sql:23:                       ^
emptest.sql:24:Bad Request: line 1:0 no viable alternative at input ';'
emptest.sql:25:Bad Request: line 1:0 no viable alternative at input ';'
emptest.sql:26:Invalid syntax at char 14
emptest.sql:26:  CREATE TABLE `emptest` (
emptest.sql:26:               ^
emptest.sql:27:Invalid syntax at char 3
emptest.sql:27:    `emp_id` int(10) NOT NULL,
emptest.sql:27:    ^
emptest.sql:28:Invalid syntax at char 3
emptest.sql:28:    `emp_city` varchar(50) NOT NULL,
emptest.sql:28:    ^
emptest.sql:29:Invalid syntax at char 3
emptest.sql:29:    `emp_name` varchar(90) NOT NULL,
emptest.sql:29:    ^
emptest.sql:30:Invalid syntax at char 3
emptest.sql:30:    `emp_phone` text NOT NULL,
emptest.sql:30:    ^
emptest.sql:31:Invalid syntax at char 3
emptest.sql:31:    `emp_sal` text NOT NULL
emptest.sql:31:    ^
emptest.sql:32:Bad Request: line 1:0 no viable alternative at input ')'
emptest.sql:33:Bad Request: line 1:0 no viable alternative at input ';'
emptest.sql:39:Invalid syntax at char 13
emptest.sql:39:  LOCK TABLES `emptest` WRITE;

Please suggest.
